### ISSUE TITLE
Better job of declaring prerequisites needed?

### ISSUE THREAD

**Issue by Bazmundi** [frapa/graph-editor#1]
windows 10
python 3.6.3
networkx 2.2
pyglet 1.3.2

Either of windows command shell or PS reports:

(networkx) PS D:\venv\networkx\graph-editor-master\graph-editor-master> python .\graph_editor.py
Traceback (most recent call last):
  File ".\graph_editor.py", line 480, in <module>
    pyglet.app.run()
  File "D:\venv\networkx\lib\site-packages\pyglet\app\__init__.py", line 138, in run
    event_loop.run()
  File "D:\venv\networkx\lib\site-packages\pyglet\app\base.py", line 142, in run
    self._run()
  File "D:\venv\networkx\lib\site-packages\pyglet\app\base.py", line 154, in _run
    timeout = self.idle()
  File "D:\venv\networkx\lib\site-packages\pyglet\app\base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "D:\venv\networkx\lib\site-packages\pyglet\window\__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "D:\venv\networkx\lib\site-packages\pyglet\event.py", line 367, in dispatch_event
    if getattr(self, event_type)(*args):
  File ".\graph_editor.py", line 172, in on_draw
    for edge in self.g.edges_iter():
AttributeError: 'Graph' object has no attribute 'edges_iter'

**Comment by code-11** [comment]
Hello from the future. I think that's a problem with the versioning of networkx. Try 2.5.1.

**Comment by frapa** [comment]
Happy to accept any tested PR with updated dependencies.
